source 'https://rubygems.org'

ruby '2.0.0'

gem 'sinatra'
gem'data_mapper'
gem 'dbi'
gem 'dbd-pg'
gem 'dm-postgres-adapter'
group :development,:test do
gem 'database_cleaner'
gem 'shotgun'
gem 'cucumber-sinatra'
gem 'capybara'
gem 'cucumber'
gem 'rspec'
end
